import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, readFileSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
const CLI = resolve(import.meta.dirname, '../scripts/module-contribution.mjs');
function run(root, ...args) { return spawnSync(process.execPath, [CLI, ...args], { cwd: root, encoding: 'utf8' }); }
function put(root, path, value) { mkdirSync(resolve(root, path, '..'), { recursive: true }); writeFileSync(join(root, path), typeof value === 'string' ? value : JSON.stringify(value)); }
function git(root, ...args) { const r = spawnSync('git', args, {cwd:root,encoding:'utf8'}); assert.equal(r.status,0,r.stderr); return r.stdout.trim(); }
function fixture(t) {
 const root=mkdtempSync(join(tmpdir(),'module-contribution-')); t.after(()=>rmSync(root,{recursive:true,force:true}));
 git(root,'init','-q'); git(root,'config','user.email','test@example.invalid'); git(root,'config','user.name','Test');
 const modules=['a','b','c'].map((id,i)=>({id,version:'1',sources:[`${id}/source.mjs`],contracts:[`${id}/contract.json`],profiles:[],tests:[`${id}/test.mjs`],dependencies:i?{[['a','b'][i-1]]:'1'}:{}}));
 for(const m of modules){put(root,m.sources[0],'export const value=1;');put(root,m.contracts[0],{});put(root,m.tests[0],"import test from 'node:test'; test('sample',()=>{}); ");}
 put(root,'examples/module-contribution/modules.json',{schemaVersion:1,modules});git(root,'add','.');git(root,'commit','-qm','initial');return {root,modules};
}
function json(result) {assert.equal(result.status,0,result.stderr);return JSON.parse(result.stdout);}
test('check validates explicit modules and graph is deterministic',t=>{const {root}=fixture(t);assert.equal(json(run(root,'check')).modules,3);const a=run(root,'graph');assert.deepEqual(json(a).edges,[{from:'b',to:'a',version:'1',kind:'semantic'},{from:'c',to:'b',version:'1',kind:'semantic'}]);assert.equal(a.stdout,run(root,'graph').stdout);});

test('impact selects own tests for internals and only direct consumers for contracts',t=>{const {root}=fixture(t);put(root,'a/source.mjs','changed');let r=json(run(root,'impact','--base','HEAD'));assert.deepEqual(r.tests,['a/test.mjs']);put(root,'a/contract.json',{changed:true});r=json(run(root,'impact','--base','HEAD'));assert.deepEqual(r.tests,['a/test.mjs','b/test.mjs']);assert.equal(r.advisory,true);});
test('impact retains deleted and renamed ownership and removed descriptor consumers',t=>{const {root,modules}=fixture(t);rmSync(join(root,'a/contract.json'));let r=json(run(root,'impact','--base','HEAD'));assert.deepEqual(r.tests,['a/test.mjs','b/test.mjs']);put(root,'a/contract.json',{});put(root,'examples/module-contribution/modules.json',{schemaVersion:1,modules:modules.slice(1).map(m=>({...m,dependencies:m.id==='b'?{}:m.dependencies}))});r=json(run(root,'impact','--base','HEAD'));assert.ok(r.affected.includes('a'));assert.ok(r.tests.includes('b/test.mjs'));});

test('release is deterministic and verifier rejects altered bytes, missing dependencies and versions',t=>{const {root,modules}=fixture(t);const release=run(root,'release');const manifest=json(release);assert.match(manifest.sourceCommit,/^[a-f0-9]{40}$/);assert.equal(run(root,'release').stdout,release.stdout);put(root,'release.json',manifest);assert.equal(json(run(root,'verify','--manifest','release.json')).valid,true);put(root,'a/source.mjs','tampered');assert.notEqual(run(root,'verify','--manifest','release.json').status,0);put(root,'a/source.mjs','export const value=1;');modules[0].version='2';put(root,'examples/module-contribution/modules.json',{schemaVersion:1,modules});assert.match(run(root,'check').stderr,/Version mismatch/);modules.shift();put(root,'examples/module-contribution/modules.json',{schemaVersion:1,modules});assert.match(run(root,'verify','--manifest','release.json').stderr,/Missing dependency/);});
test('invalid paths and symlinks are denied',t=>{const {root,modules}=fixture(t);modules[0].sources=['../escape'];put(root,'examples/module-contribution/modules.json',{schemaVersion:1,modules});assert.match(run(root,'check').stderr,/Invalid path/);modules[0].sources=['a/link'];symlinkSync('/etc/passwd',join(root,'a/link'));put(root,'examples/module-contribution/modules.json',{schemaVersion:1,modules});assert.match(run(root,'check').stderr,/Symlink/);});

test('scaffold creates runnable template without overwrite or traversal',t=>{const {root}=fixture(t);const result=json(run(root,'scaffold','sample'));assert.match(result.next,/node --test/);const r=spawnSync(process.execPath,['--test','examples/module-contribution/sample/test.mjs'],{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.notEqual(run(root,'scaffold','sample').status,0);assert.notEqual(run(root,'scaffold','../escape').status,0);assert.equal(json(run(root,'check','--descriptor','examples/module-contribution/sample/modules.json')).modules,1);});

test('impact retains ownership when a declared directory becomes empty',t=>{const {root,modules}=fixture(t);modules[0].sources=['a/src'];modules[0].tests=['a/tests'];put(root,'a/src/value.mjs','export const value=1;');put(root,'a/tests/value.mjs',"import test from 'node:test'; test('value',()=>{});");put(root,'examples/module-contribution/modules.json',{schemaVersion:1,modules});git(root,'add','.');git(root,'commit','-qm','directory ownership');rmSync(join(root,'a/src/value.mjs'));let plan=json(run(root,'impact','--base','HEAD'));assert.deepEqual(plan.affected,['a']);assert.deepEqual(plan.tests,['a/tests/value.mjs']);assert.notEqual(run(root,'check').status,0);rmSync(join(root,'a/tests/value.mjs'));plan=json(run(root,'impact','--base','HEAD'));assert.deepEqual(plan.missingTests,['a/tests/value.mjs']);assert.notEqual(run(root,'release').status,0);});

test('test command runs selected checks and propagates real failures',t=>{const {root}=fixture(t);put(root,'a/source.mjs','changed');let result=json(run(root,'test','--base','HEAD'));assert.deepEqual(result.tests,['a/test.mjs']);assert.equal(result.executed,true);put(root,'a/test.mjs',"import test from 'node:test'; test('broken',()=>{throw new Error('expected negative');});");assert.notEqual(run(root,'test','--base','HEAD').status,0);});

test('graph derives workspace dependencies without pretending ranges are solved',t=>{const {root}=fixture(t);put(root,'package.json',{workspaces:['packages/*']});put(root,'packages/one/package.json',{name:'one',version:'1.0.0'});put(root,'packages/two/package.json',{name:'two',version:'1.0.0',dependencies:{one:'^1.0.0',external:'2'}});const graph=json(run(root,'graph'));assert.deepEqual(graph.npm.edges,[{from:'two',to:'one',range:'^1.0.0',kind:'dependencies'}]);assert.equal(graph.npm.versionResolution,'not performed');});

test('impact plans a removed provider even while surviving descriptor has dangling dependency',t=>{const {root,modules}=fixture(t);put(root,'examples/module-contribution/modules.json',{schemaVersion:1,modules:modules.slice(1)});const r=json(run(root,'impact','--base','HEAD'));assert.deepEqual(r.tests,['a/test.mjs','b/test.mjs']);assert.notEqual(run(root,'check').status,0);});
test('rename, complete descriptor removal, invalid manifests and symlink ancestors fail safely',t=>{const {root}=fixture(t);git(root,'mv','a/contract.json','a/renamed.json');assert.deepEqual(json(run(root,'impact','--base','HEAD')).tests,['a/test.mjs','b/test.mjs']);git(root,'reset','--hard','HEAD');const m=json(run(root,'release'));m.files[0].path='../outside';put(root,'release.json',m);assert.notEqual(run(root,'verify','--manifest','release.json').status,0);rmSync(join(root,'examples/module-contribution/modules.json'));assert.deepEqual(json(run(root,'impact','--base','HEAD')).affected,['a','b','c']);rmSync(join(root,'examples/module-contribution'),{recursive:true});symlinkSync(tmpdir(),join(root,'examples/module-contribution'));assert.match(run(root,'scaffold','unsafe').stderr,/Symlink/);});
