import { createHash } from "node:crypto";

export const ORDERED_STORY_STEP_IDS = Object.freeze(Array.from({ length: 23 }, (_, index) => `CKS-12-P2-SS-${String(index + 1).padStart(2, "0")}`));
export const REQUIRED_PACKAGE_HEADS = Object.freeze(["PREREQUISITE_BIND", "EMPTY_KB_ACQUISITION", "GOVERNED_PROMOTION", "EXPERIENCE_DIVERSITY", "READONLY_KALEIDOSPHERE", "SHADOW_WORKFLOW", "FUNCTION_COST_PARITY", "DRIFT_FASTPATH"]);
export const COMPONENT_VERSIONS = Object.freeze({ reportSchema: "v1", metricModel: "cks-12-falsification-metrics@v1", verifier: "cks-12-falsification-validator@v1" });
export const DENIAL_CODES = Object.freeze(["MISSING_INPUT", "VERSION_LOCK_MISMATCH", "STORY_STEP_COVERAGE_FAILED", "PACKAGE_HEAD_MISSING", "QUALITY_GATE_FAILED", "RECALL_GATE_FAILED", "FALSE_COMPLETENESS_DETECTED", "ATTRIBUTION_GATE_FAILED", "COST_GATE_FAILED", "FALSIFICATION_METRICS_INCOMPLETE", "STOP_CONDITION_MET"] as const);
type DenialCode = typeof DENIAL_CODES[number]; type RecordValue = Record<string, unknown>;
export type ValidationOutcome = { status: "PASS_SYNTHETIC_ONLY"; orderedStoryStepIds: readonly string[]; packageHeadIds: readonly string[]; authority: "NONE"; capabilityDelta: "NONE"; effect: "NONE"; productionClaimed: false } | { status: "FALSIFIED"; reasonCodes: readonly DenialCode[]; details: readonly string[]; authority: "NONE"; capabilityDelta: "NONE"; effect: "NONE" };
export function canonicalJson(value: unknown): string { if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value); if (typeof value === "number") { if (!Number.isFinite(value)) throw new TypeError("non-finite number"); return JSON.stringify(value); } if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (typeof value !== "object" || Object.getPrototypeOf(value) !== Object.prototype) throw new TypeError("plain JSON required"); const object = value as RecordValue; return `{${Object.keys(object).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(object[key])}`).join(",")}}`; }
export const digest = (value: unknown): string => createHash("sha256").update(canonicalJson(value)).digest("hex");
const record = (value: unknown): value is RecordValue => value !== null && typeof value === "object" && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype;
const ratioIsOne = (value: unknown): boolean => record(value) && value.numerator === value.denominator && typeof value.numerator === "number" && value.numerator > 0;
const deny = (reasonCodes: DenialCode[], details: string[]): ValidationOutcome => ({ status: "FALSIFIED", reasonCodes: [...new Set(reasonCodes)].sort(), details, authority: "NONE", capabilityDelta: "NONE", effect: "NONE" });
/** Validates the final report. It is deliberately evidence-only and never grants authority. */
export function validateFalsificationReport(input: unknown): ValidationOutcome {
  if (!record(input)) return deny(["MISSING_INPUT"], ["report must be a plain JSON object"]);
  const reasons: DenialCode[] = []; const details: string[] = []; const add = (code: DenialCode, detail: string) => { reasons.push(code); details.push(detail); };
  if (!record(input.componentVersions) || canonicalJson(input.componentVersions) !== canonicalJson(COMPONENT_VERSIONS)) add("VERSION_LOCK_MISMATCH", "component versions must exactly match the frozen lock");
  if (!Array.isArray(input.orderedStoryStepIds) || canonicalJson(input.orderedStoryStepIds) !== canonicalJson(ORDERED_STORY_STEP_IDS)) add("STORY_STEP_COVERAGE_FAILED", "all 23 ordered story steps are required exactly once");
  const heads = input.packageHeads;
  if (!Array.isArray(heads) || canonicalJson(heads) !== canonicalJson(REQUIRED_PACKAGE_HEADS)) add("PACKAGE_HEAD_MISSING", "accepted package heads are missing, stale, conflicting, unauthorized, or untested");
  const metrics = input.metrics;
  if (!record(metrics) || !ratioIsOne(metrics.quality) || (metrics.quality as RecordValue).numerator !== 3) add("QUALITY_GATE_FAILED", "quality requires 3/3 applicable holdouts");
  if (!record(metrics) || !ratioIsOne(metrics.criticalRequirementRecall) || !ratioIsOne(metrics.totalRequirementRecall)) add("RECALL_GATE_FAILED", "critical and total requirement recall must both be 1/1");
  if (!record(metrics) || !record(metrics.falseCompleteness) || (metrics.falseCompleteness as RecordValue).candidateIncorrectSufficient !== 0 || !Number.isInteger((metrics.falseCompleteness as RecordValue).baselineIncorrectSufficient) || ((metrics.falseCompleteness as RecordValue).baselineIncorrectSufficient as number) < 1) add("FALSE_COMPLETENESS_DETECTED", "candidate false completeness must be zero and baseline must contain a known failure");
  if (!record(metrics) || !ratioIsOne(metrics.attribution) || !Array.isArray(metrics.attributedFailureClasses) || !["APPLICABILITY", "DRIFT"].every((value) => (metrics.attributedFailureClasses as unknown[]).includes(value))) add("ATTRIBUTION_GATE_FAILED", "attribution evidence must include exact Applicability and drift failures");
  const cost = record(metrics) && record(metrics.cost) ? metrics.cost : undefined;
  if (!cost || !Number.isInteger(cost.functionReasoningTokens) || !Number.isInteger(cost.workflowReasoningTokens) || !Number.isInteger(cost.functionRetrievalCalls) || !Number.isInteger(cost.workflowRetrievalCalls) || !Number.isInteger(cost.functionVerifierChecks) || !Number.isInteger(cost.workflowVerifierChecks) || (cost.functionReasoningTokens as number) >= (cost.workflowReasoningTokens as number) || (cost.functionRetrievalCalls as number) >= (cost.workflowRetrievalCalls as number) || (cost.functionVerifierChecks as number) < (cost.workflowVerifierChecks as number)) add("COST_GATE_FAILED", "Function cost must strictly improve reasoning and retrieval without reducing verification");
  const requiredMetricRecords = ["storyReplay", "repetitionGeneralization", "kaleidoSphereBoundary", "shadowParity", "functionParity", "revalidationAbort", "boundaryDenials", "confusion", "rawCounts"];
  if (!record(metrics) || requiredMetricRecords.some((key) => !record(metrics[key])) || !Array.isArray(metrics.runExclusions) || !Number.isInteger(metrics.abstentions) || !Number.isInteger(metrics.unresolvedCases) || !Number.isInteger(metrics.missingReceiptCount) || !Number.isInteger(metrics.invalidReceiptCount)) add("FALSIFICATION_METRICS_INCOMPLETE", "report must retain replay, diversity, boundary, parity, revalidation, denial, confusion, raw-count, abstention, unresolved, receipt, and exclusion metrics");
  if (record(metrics)) {
    const replay = metrics.storyReplay as RecordValue; const diversity = metrics.repetitionGeneralization as RecordValue; const boundary = metrics.kaleidoSphereBoundary as RecordValue; const shadow = metrics.shadowParity as RecordValue; const fn = metrics.functionParity as RecordValue; const drift = metrics.revalidationAbort as RecordValue; const denials = metrics.boundaryDenials as RecordValue;
    if (replay.cleanReplays !== 3 || replay.identicalDigestSets !== true || diversity.operationalRepetitions !== 3 || diversity.generalizationStrata !== 3 || diversity.untouchedHoldouts !== 1 || boundary.forbiddenFields !== 0 || boundary.inventedEdges !== 0 || boundary.canonicalMutations !== 0 || shadow.applicableHoldouts !== 3 || shadow.unexpectedMismatches !== 0 || fn.replaysPerHoldout !== 3 || fn.missingProofObligations !== 0 || drift.oldVersionFastPathSuccesses !== 0 || drift.deniedAttemptCount !== 2 || denials.unexpectedSuccesses !== 0) add("FALSIFICATION_METRICS_INCOMPLETE", "minimum exact falsification denominators and zero-failure counts are not met");
  }
  if (!Array.isArray(input.stopConditions) || input.stopConditions.length < 9 || !Array.isArray(input.encounteredStopConditions) || input.encounteredStopConditions.length !== 0) add("STOP_CONDITION_MET", "report must declare every stop condition and record none encountered");
  if (input.authority !== "NONE" || input.capabilityDelta !== "NONE" || input.effect !== "NONE" || input.productionClaimed !== false) add("STOP_CONDITION_MET", "the report cannot carry authority, capability, effect, or production claims");
  if (reasons.length) return deny(reasons, details);
  return Object.freeze({ status: "PASS_SYNTHETIC_ONLY", orderedStoryStepIds: [...ORDERED_STORY_STEP_IDS], packageHeadIds: [...REQUIRED_PACKAGE_HEADS], authority: "NONE", capabilityDelta: "NONE", effect: "NONE", productionClaimed: false });
}
export function createReceipt(fixtureSha256: string, result: ValidationOutcome): RecordValue { if (!/^[0-9a-f]{64}$/.test(fixtureSha256)) throw new TypeError("fixture digest must be lowercase SHA-256"); const body = { schemaVersion: "chimpmaera.cks/falsification-report-receipt/v1", receiptId: "CKS-12-FALSIFICATION-REPORT-RECEIPT-V1", fixtureSha256, componentVersions: COMPONENT_VERSIONS, result, status: "RECORDED", authority: "NONE", capabilityDelta: "NONE", effect: "NONE" }; return { ...body, receiptSha256: digest(body) }; }
